#!/usr/bin/env python3
"""List every input key the solver reads, with its type, default and the routine that reads it.

The list is extracted from the calls to MIO_InputParameter, MIO_InputFindBlock and
MIO_InputBlock in lanczosKuboCode/Src; nothing is maintained by hand. A key read in several
routines is listed once per distinct default, because the default can differ between them.

    python3 tools/input/list_input_keys.py            # writes docs/user-guide/input-keys.md
    python3 tools/input/list_input_keys.py --check    # exit 1 if that file is out of date
"""
import argparse
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
SRC = os.path.join(ROOT, "lanczosKuboCode", "Src")
OUT = os.path.join(ROOT, "docs", "user-guide", "input-keys.md")

CALL = re.compile(r"MIO_InputParameter\s*\(\s*'([^']+)'\s*,\s*([^,]+?)\s*,\s*(.+)\)\s*(?:!\s*(.*))?$", re.I)
BLOCK = re.compile(r"MIO_Input(?:FindBlock|Block)\s*\(\s*'([^']+)'", re.I)
ROUTINE = re.compile(r"^\s*(?:recursive\s+)?(subroutine|function)\s+(\w+)", re.I)


def kind(default):
    d = default.strip()
    if d.lower() in (".true.", ".false."):
        return "logical"
    if re.fullmatch(r"'[^']*'|\"[^\"]*\"", d):
        return "string"
    if re.fullmatch(r"[-+]?\d+", d):
        return "integer"
    if re.fullmatch(r"[-+]?(\d+\.\d*|\.\d+|\d+)([eEdD][-+]?\d+)?(_dp)?", d):
        return "real"
    return ""


def split_default(rest):
    """`rest` is everything after the variable: the default expression, possibly with nested parentheses."""
    depth, out = 0, ""
    for ch in rest:
        if ch == "(":
            depth += 1
        elif ch == ")":
            if depth == 0:
                break
            depth -= 1
        out += ch
    return out.strip()


def collect():
    rows, blocks = {}, {}
    for folder, _, files in os.walk(SRC):
        for name in sorted(files):
            if not name.lower().endswith((".f90", ".inc")) or "MIO" in os.path.relpath(folder, SRC).split(os.sep):
                continue
            routine = "-"
            for line in open(os.path.join(folder, name), errors="replace"):
                code = line.split("!")[0] if line.lstrip().startswith("!") else line
                m = ROUTINE.match(code)
                if m:
                    routine = m.group(2)
                if code.lstrip().startswith("!"):
                    continue
                for m in re.finditer(r"MIO_InputParameter\s*\(\s*'([^']+)'\s*,\s*([^,]+?)\s*,(.*)", code, re.I):
                    key, default = m.group(1), split_default(m.group(3))
                    default = re.sub(r"_dp\b", "", default)
                    rows.setdefault((key.lower(), default), [key, default, kind(m.group(3) and split_default(m.group(3))), []])[3].append(
                        f"{name}: {routine}")
                for m in BLOCK.finditer(code):
                    blocks.setdefault(m.group(1).lower(), [m.group(1), []])[1].append(f"{name}: {routine}")
    return rows, blocks


def render():
    rows, blocks = collect()
    keys = {}
    for (k, _), row in rows.items():
        keys.setdefault(k, []).append(row)
    out = ["# Input keys", "",
           "Generated by `tools/input/list_input_keys.py` from the source; do not edit by hand.", "",
           f"{len(keys)} keys and {len(blocks)} blocks are read by the solver. A key is written as `Key value` on one line of",
           "the input file; a block as `&begin Name N` ... `&end Name`. Keys are not case sensitive. If a key appears",
           "more than once, the first value is used and the solver prints a warning. A key that is not listed here is",
           "not read; the keys of the input file that the run did not read are listed at the end of the output.", "",
           "The default shown is the expression in the source; where it is not a literal, it is computed from other",
           "input. \"Read in\" names the source file and routine, which is where to look for what the key does: most",
           "keys have no other documentation yet.", "",
           "| Key | Type | Default | Read in |", "| --- | --- | --- | --- |"]
    for k in sorted(keys):
        for key, default, typ, where in sorted(keys[k], key=lambda r: r[1]):
            places = sorted(set(where))
            shown = "; ".join(places[:3]) + (f"; ... ({len(places)} places)" if len(places) > 3 else "")
            out.append(f"| `{key}` | {typ} | `{default.replace('|', '/')}` | {shown} |")
    out += ["", "## Blocks", "", "| Block | Read in |", "| --- | --- |"]
    for k in sorted(blocks):
        name, where = blocks[k]
        out.append(f"| `{name}` | {'; '.join(sorted(set(where))[:3])} |")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    p.add_argument("--check", action="store_true")
    a = p.parse_args()
    text = render()
    if a.check:
        ok = os.path.exists(OUT) and open(OUT).read() == text
        print("input-keys.md is up to date" if ok else "input-keys.md is OUT OF DATE: run tools/input/list_input_keys.py")
        sys.exit(0 if ok else 1)
    open(OUT, "w").write(text)
    print(f"wrote {os.path.relpath(OUT, ROOT)}: {text.count(chr(10))} lines")
